
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  objectEnumValues,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 6.16.2
 * Query Engine version: 1c57fdcd7e44b29b9313256c76699e91c3ac3c43
 */
Prisma.prismaVersion = {
  client: "6.16.2",
  engine: "1c57fdcd7e44b29b9313256c76699e91c3ac3c43"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = objectEnumValues.instances.DbNull
Prisma.JsonNull = objectEnumValues.instances.JsonNull
Prisma.AnyNull = objectEnumValues.instances.AnyNull

Prisma.NullTypes = {
  DbNull: objectEnumValues.classes.DbNull,
  JsonNull: objectEnumValues.classes.JsonNull,
  AnyNull: objectEnumValues.classes.AnyNull
}



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.UserScalarFieldEnum = {
  id: 'id',
  firstName: 'firstName',
  lastName: 'lastName',
  email: 'email',
  password: 'password',
  bio: 'bio',
  availability: 'availability',
  position: 'position',
  rate: 'rate',
  languages: 'languages',
  skills: 'skills',
  pictures: 'pictures',
  role: 'role',
  isVerified: 'isVerified',
  isTwoFactorEnabled: 'isTwoFactorEnabled',
  method: 'method',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.AccauntScalarFieldEnum = {
  id: 'id',
  type: 'type',
  provider: 'provider',
  refreshToken: 'refreshToken',
  accessToken: 'accessToken',
  expiresAt: 'expiresAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  userId: 'userId'
};

exports.Prisma.TokenScalarFieldEnum = {
  id: 'id',
  email: 'email',
  token: 'token',
  type: 'type',
  expiresIn: 'expiresIn'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};
exports.AvailabilityStatus = exports.$Enums.AvailabilityStatus = {
  AVAILABLE: 'AVAILABLE',
  UNAVAILABLE: 'UNAVAILABLE',
  PART_TIME: 'PART_TIME'
};

exports.UserRole = exports.$Enums.UserRole = {
  ADMIN: 'ADMIN',
  USER: 'USER',
  GUEST: 'GUEST'
};

exports.AuthMethod = exports.$Enums.AuthMethod = {
  EMAIL: 'EMAIL',
  GOOGLE: 'GOOGLE',
  GITHUB: 'GITHUB',
  LINKEDIN: 'LINKEDIN'
};

exports.UserPosition = exports.$Enums.UserPosition = {
  UNSELECTED: 'UNSELECTED',
  FRONTEND_DEVELOPER: 'FRONTEND_DEVELOPER',
  BACKEND_DEVELOPER: 'BACKEND_DEVELOPER',
  FULLSTACK_DEVELOPER: 'FULLSTACK_DEVELOPER',
  MOBILE_DEVELOPER: 'MOBILE_DEVELOPER',
  DEVOPS_ENGINEER: 'DEVOPS_ENGINEER',
  SITE_RELIABILITY_ENGINEER: 'SITE_RELIABILITY_ENGINEER',
  QA_ENGINEER: 'QA_ENGINEER',
  QA_AUTOMATION_ENGINEER: 'QA_AUTOMATION_ENGINEER',
  QA_MANUAL_ENGINEER: 'QA_MANUAL_ENGINEER',
  SOFTWARE_ARCHITECT: 'SOFTWARE_ARCHITECT',
  DATA_ENGINEER: 'DATA_ENGINEER',
  DATA_SCIENTIST: 'DATA_SCIENTIST',
  MACHINE_LEARNING_ENGINEER: 'MACHINE_LEARNING_ENGINEER',
  AI_ENGINEER: 'AI_ENGINEER',
  SYSTEM_ADMINISTRATOR: 'SYSTEM_ADMINISTRATOR',
  NETWORK_ENGINEER: 'NETWORK_ENGINEER',
  DATABASE_ADMINISTRATOR: 'DATABASE_ADMINISTRATOR',
  SECURITY_ENGINEER: 'SECURITY_ENGINEER',
  CLOUD_ENGINEER: 'CLOUD_ENGINEER',
  UX_UI_DEVELOPER: 'UX_UI_DEVELOPER',
  UX_DESIGNER: 'UX_DESIGNER',
  UI_DESIGNER: 'UI_DESIGNER',
  FRONTEND_ARCHITECT: 'FRONTEND_ARCHITECT',
  BACKEND_ARCHITECT: 'BACKEND_ARCHITECT',
  PRODUCT_DEVELOPER: 'PRODUCT_DEVELOPER',
  PROJECT_MANAGER: 'PROJECT_MANAGER',
  PRODUCT_MANAGER: 'PRODUCT_MANAGER',
  BUSINESS_ANALYST: 'BUSINESS_ANALYST',
  SCRUM_MASTER: 'SCRUM_MASTER',
  TECHNICAL_WRITER: 'TECHNICAL_WRITER',
  CUSTOMER_SUCCESS_MANAGER: 'CUSTOMER_SUCCESS_MANAGER',
  SALES_ENGINEER: 'SALES_ENGINEER',
  SALES_REPRESENTATIVE: 'SALES_REPRESENTATIVE',
  MARKETING_MANAGER: 'MARKETING_MANAGER',
  HR_SPECIALIST: 'HR_SPECIALIST',
  SUPPORT_SPECIALIST: 'SUPPORT_SPECIALIST',
  OPERATIONS_MANAGER: 'OPERATIONS_MANAGER',
  ACCOUNT_MANAGER: 'ACCOUNT_MANAGER',
  DESIGN_MANAGER: 'DESIGN_MANAGER',
  UX_RESEARCHER: 'UX_RESEARCHER'
};

exports.Skill = exports.$Enums.Skill = {
  HTML: 'HTML',
  CSS: 'CSS',
  JAVASCRIPT: 'JAVASCRIPT',
  TYPESCRIPT: 'TYPESCRIPT',
  REACT: 'REACT',
  NEXTJS: 'NEXTJS',
  VUE: 'VUE',
  ANGULAR: 'ANGULAR',
  SVELTE: 'SVELTE',
  REDUX: 'REDUX',
  MOBX: 'MOBX',
  TAILWINDCSS: 'TAILWINDCSS',
  BOOTSTRAP: 'BOOTSTRAP',
  MATERIAL_UI: 'MATERIAL_UI',
  STORYBOOK: 'STORYBOOK',
  TESTING_LIBRARY: 'TESTING_LIBRARY',
  JEST: 'JEST',
  CYPRESS: 'CYPRESS',
  NODEJS: 'NODEJS',
  NESTJS: 'NESTJS',
  EXPRESS: 'EXPRESS',
  KOA: 'KOA',
  PYTHON: 'PYTHON',
  DJANGO: 'DJANGO',
  FLASK: 'FLASK',
  RUBY: 'RUBY',
  RUBY_ON_RAILS: 'RUBY_ON_RAILS',
  PHP: 'PHP',
  LARAVEL: 'LARAVEL',
  SYMFONY: 'SYMFONY',
  JAVA: 'JAVA',
  SPRING: 'SPRING',
  CSHARP: 'CSHARP',
  DOTNET: 'DOTNET',
  GO: 'GO',
  RUST: 'RUST',
  SQL: 'SQL',
  POSTGRESQL: 'POSTGRESQL',
  MYSQL: 'MYSQL',
  MONGODB: 'MONGODB',
  REDIS: 'REDIS',
  GRAPHQL: 'GRAPHQL',
  REST: 'REST',
  MICROservices: 'MICROservices',
  DOCKER: 'DOCKER',
  KUBERNETES: 'KUBERNETES',
  AWS: 'AWS',
  GCP: 'GCP',
  AZURE: 'AZURE',
  CI_CD: 'CI_CD',
  GIT: 'GIT',
  SVN: 'SVN',
  TESTING: 'TESTING',
  UNIT_TESTS: 'UNIT_TESTS',
  INTEGRATION_TESTS: 'INTEGRATION_TESTS',
  END_TO_END_TESTS: 'END_TO_END_TESTS',
  MANUAL_TESTING: 'MANUAL_TESTING',
  AUTOMATION_TESTING: 'AUTOMATION_TESTING',
  SELENIUM: 'SELENIUM',
  CYPRESS_QA: 'CYPRESS_QA',
  POSTMAN: 'POSTMAN',
  JIRA: 'JIRA',
  TESTRAIL: 'TESTRAIL',
  QA_ANALYSIS: 'QA_ANALYSIS',
  LINUX: 'LINUX',
  WINDOWS_SERVER: 'WINDOWS_SERVER',
  NETWORKING: 'NETWORKING',
  SECURITY: 'SECURITY',
  FIREWALL: 'FIREWALL',
  VPN: 'VPN',
  MONITORING: 'MONITORING',
  PROMETHEUS: 'PROMETHEUS',
  GRAFANA: 'GRAFANA',
  ANSIBLE: 'ANSIBLE',
  TERRAFORM: 'TERRAFORM',
  DATA_ANALYSIS: 'DATA_ANALYSIS',
  DATA_ENGINEERING: 'DATA_ENGINEERING',
  DATA_SCIENCE: 'DATA_SCIENCE',
  MACHINE_LEARNING: 'MACHINE_LEARNING',
  DEEP_LEARNING: 'DEEP_LEARNING',
  PYTORCH: 'PYTORCH',
  TENSORFLOW: 'TENSORFLOW',
  SCIKIT_LEARN: 'SCIKIT_LEARN',
  PANDAS: 'PANDAS',
  NUMPY: 'NUMPY',
  MATPLOTLIB: 'MATPLOTLIB',
  SEABORN: 'SEABORN',
  NLP: 'NLP',
  COMPUTER_VISION: 'COMPUTER_VISION',
  BIG_DATA: 'BIG_DATA',
  SPARK: 'SPARK',
  HADOOP: 'HADOOP',
  UX_DESIGN: 'UX_DESIGN',
  UI_DESIGN: 'UI_DESIGN',
  Figma: 'Figma',
  Sketch: 'Sketch',
  Adobe_XD: 'Adobe_XD',
  Photoshop: 'Photoshop',
  Illustrator: 'Illustrator',
  PROTOTYPING: 'PROTOTYPING',
  USER_RESEARCH: 'USER_RESEARCH',
  USABILITY_TESTING: 'USABILITY_TESTING',
  PROJECT_MANAGEMENT: 'PROJECT_MANAGEMENT',
  PRODUCT_MANAGEMENT: 'PRODUCT_MANAGEMENT',
  SCRUM: 'SCRUM',
  KANBAN: 'KANBAN',
  AGILE: 'AGILE',
  BUSINESS_ANALYSIS: 'BUSINESS_ANALYSIS',
  TECHNICAL_WRITING: 'TECHNICAL_WRITING',
  CUSTOMER_SUCCESS: 'CUSTOMER_SUCCESS',
  SALES: 'SALES',
  MARKETING: 'MARKETING',
  HR: 'HR',
  OPERATIONS: 'OPERATIONS',
  ACCOUNT_MANAGEMENT: 'ACCOUNT_MANAGEMENT',
  COMMUNICATION: 'COMMUNICATION',
  LEADERSHIP: 'LEADERSHIP'
};

exports.TokenType = exports.$Enums.TokenType = {
  EMAIL_VERIFICATION: 'EMAIL_VERIFICATION',
  PASSWORD_RESET: 'PASSWORD_RESET',
  TWO_FACTOR_AUTH: 'TWO_FACTOR_AUTH'
};

exports.Prisma.ModelName = {
  User: 'User',
  Accaunt: 'Accaunt',
  Token: 'Token'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
